root: true
env:
  commonjs: true
  es6: true
  node: true
extends:
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 11
rules:
  eol-last: error
  eqeqeq: [error, allow-null]
  indent: [error, 4, { SwitchCase: 1 }]
  no-trailing-spaces: error
  no-var: error
  no-unused-vars: [error, { vars: all, args: none, ignoreRestSiblings: true }]
  semi: [2, always]
